### ISSUE TITLE
is there any document for this?

### ISSUE THREAD

**Issue by shuaiwang88** [gwr3n/inventoryanalytics#1]

**Comment by gwr3n** [comment]
An open access textbook is under review.

**Comment by shuaiwang88** [comment]
Thanks! May I have a sneak peek for the draft? I am doing  academic research on the inventory. Thanks!
On Feb 7, 2021, 8:29 AM -0500, Roberto Rossi <notifications@github.com>, wrote:

An open access textbook is under review.

**Comment by gwr3n** [comment]
I have added the book to my Google Drive.

https://drive.google.com/file/d/1cdQ0DfxnAM2FAr3_htAnPbfBbHP9vG6P/view?usp=sharing

With this link you will be able to browse the book, but you will not be able to download or print it. 

I will post the doi once the book is in press.

**Comment by shuaiwang88** [comment]
Thank you! Much appreciated!
On Feb 7, 2021, 9:56 AM -0500, Roberto Rossi <notifications@github.com>, wrote:

I have added the book to my Google Drive.

https://drive.google.com/file/d/1cdQ0DfxnAM2FAr3_htAnPbfBbHP9vG6P/view?usp=sharing<https://urldefense.com/v3/__https://drive.google.com/file/d/1cdQ0DfxnAM2FAr3_htAnPbfBbHP9vG6P/view?usp=sharing__;!!On18fmf1aQ!kFda8bCdNDFWTy9zcGFM5HLWMTmGxMuVB6rbfiMQGOjqvVEa3N6ReJLQu4PF48BkIUSR$>

With this link you will be able to browse the book, but you will not be able to download or print it.

I will post the doi once the book is in press.

**Comment by gwr3n** [comment]
The book is now published https://www.openbookpublishers.com/product/1399
